- src/tiaz0128/ch_05/solution_001.py
3분
- list 내장 메소드 : `sort`
- 파이썬 내장 함수 : `sorted`
- 리스트 정렬에는 `sort`  또는 `sorted`
1. 배열 내장 메서드는 리턴값이 `None` 이라는걸 몰랐음
2. 그래서 정렬과 동시에 리턴하면 안됌
1. `sort` : O(n log n)
2. `sorted` : O(n log n)
- 없음
- 코딩 테스트 할때는, 정확하게 파이썬 기본 내장 함수 사용법을 기억 필요.
> 문제 001 : 배열 정렬하기

- src/youngrongoh/ch_05/solution_001.py
15분
파이썬 빌트인 메서드
처음에 정렬 로직을 직접 구현했다가 O(N^2) 복잡도가 나와서 빌트인 메서드로 변경했습니다.
O(NlogN)
테스트 케이스는 추가하지 않았습니다.
- 빌트인 메서드를 적극적으로 활용 해야겠습니다.
- 아직 제약조건을 보고 시간 복잡도를 어느정도까지 가져갈 수 있는지 판단하는 것이 부족합니다.
> ch_05-001. 배열 정렬하기

- src/youngrongoh/ch_05/solution_002.py
3분
리스트, 셋, `sort()` + `reverse`
- "중복값을 제거"하라는 조건에 따라 셋을 사용했습니다.
- 내림차순 정렬을 위해 sort 메서드의 reverse 인자를 전달했습니다.
O(NlogN)
없습니다.
`sort`는 뮤터블 메서드라서 원본 값을 변경하게 되어 나중에 복잡한 구현에서는 의도치 않은 동작이 발생 할 수 있을 것 같습니다. 이번에는 셋을 리스트로 바꾸면서 복사 되었지만, 이러한 경우가 아닐 때도 대비하여, 항상 정렬 전에 데이터를 복사해서 쓰거나, 이뮤터블 메서드를 사용하는 것이 좋을 것 같습니다.
> ch_05-002. 배열 제어하기

- src/youngrongoh/ch_05/solution_003.py
10분
셋, 리스트, 빌트인 `sort()`
- 셋을 사용한 이유
- 예시 입력과 결과를 보니 결과에서 중복이 제거된 것이 보였습니다.
- 오름차순 정렬을 위해 빌트인 `sort()`를 사용했습니다.
$O(N^2log(N)^2)$
추가하지 않았습니다.
입력이 0과 100이하의 자연수로 한정되어서 예시 입력 외에 추가 케이스를 확인할 필요는 없다고 판단했습니다.
- 중첩 반복문에서 반복 횟수가 동적으로 바뀌는데 시간 복잡도가 여전히 $O(N^2)$이라는 것이 잘 이해되지 않습니다.
- 정렬에 대한 시간 복잡도가 $O(N^2log(N)^2)$이라는 것을 잘 이해하지 못했습니다.
- 문제 풀이 후 책에 있는 답안을 보면서 `sorted`를 통해 새로운 정렬 시퀀스 객체를 얻을 수 있다는 것을 알게 되었습니다.
> ch_05-003. 두 개 뽑아서 더하기

- src/youngrongoh/ch_05/solution_004.py
10분
리스트, 완전 탐색
- 완전 탐색
- "1번 문제부터 마지막 문제까지"라는 조건이 있기 때문에 문제의 답안에 대해 완전 탐색이 필요합니다.
$O(N)$
- 두 개의 반복문이 중첩되어 있지만, 수포자의 패턴($M$)은 <ins>세 가지</ins>로 고정되어 있기 다음과 같이 볼 수 있습니다.
$$O(N) * O(M) = O(N) * O(3) = O(N)$$
없습니다.
- 예시 결과 2에서 동점인 케이스도 확인하고 있어서 추가하지 않았습니다.
> ch_05-004. 모의고사

- src/youngrongoh/ch_05/solution_005.py
1시간 이상
리스트
- 행렬의 곱셈을 어떻게 하는지 잊어버려서 관련 수학 개념을 찾아봤습니다.
- 앞에 행렬의 각 열과 뒤의 행렬의 각 행을 곱하는 과정을 삼중 반복문으로 구현하는 것이 헷갈렸습니다. 풀긴 했지만 책에 나온 답안과는 방식이 조금 다릅니다. 다시 풀려고 하면 여전히 혼란스러울 것 같아서 여러 번 반복해서 풀어봐야겠습니다.
$O(N^3)$
- arr1과 arr2이 가질 수 있는 행과 열 조건이 동일하기 때문에 최악의 케이스를 상정하면 두 행렬의 행과 열의 길이는 모두 최대값 N으로 볼 수 있습니다.
- 삼중 반복문을 수행하고 있습니다.
추가하지 않았습니다.
- 수학 개념을 학습하고 이를 구현으로 옮기느라 신경쓰지 못했습니다.
- 잊어버린 수학 개념에 대한 학습이 필요합니다.
> ch_05-005. 행렬의 곱셈

- src/youngrongoh/ch_05/solution_006.py
30분
리스트, 빌트인 `sort()`
- `stages`의 길이가 사용자 수라는 것을 처음 문제를 보았을 때는 알지 못했습니다.
$O(M + N\log_{}N)$
- 스테이지 전체($N$)를 순회하고, 스테이지에 머물러 있는 사용자 전체($M$)을 순회합니다.
- 스테이지 전체에 대해 빌트인 정렬을 합니다.
따라서, 다음과 같습니다.
$$O(N) + O(M) + O(N\log_{}N) = O(M) + O(N\log_{}N) = O(M + N\log_{}N)$$
없습니다.
- 테스트 케이스를 추가로 생각하지 못했습니다.
- 입출력 값만 보는 것이 아니라, 함께 나온 설명도 잘 읽어 보아야겠습니다.
> ch_05-006. 실패율

- src/youngrongoh/ch_05/solution_007.py
50분
리스트, 튜플, 셋, 딕셔너리
- 튜플
- 명령어에 관련된 상수 `movements`와 이전에 방문한 경로의 좌표를 변경할 수 없도록 하기 위해 사용했습니다.
- 셋
- 중복을 제거하기 위해 사용했습니다.
- 이전에 지나갔던 경로에 대한 중복을 제거하는 것이 어려웠습니다.
- 시작점부터 지나온 모든 좌표를 저장 해두고 셋을 이용해서 이 점들의 중복을 제거하는 방식으로 구현 해보았습니다. 하지만 경로의 개수를 구하는 문제이기 때문에 점의 개수를 파악하는 것은 옳은 방법이 아니었습니다.
- 반복문을 중첩해서 앞의 좌표와 뒤의 좌표의 묶음, 그리고 두 좌표의 순서를 바꾼 묶음을 만들어 중복을 체크해야하는 것인지 고민해봤지만, 반복문이 중첩되는 순간 복잡도는 O(N^2)이 되어서 이 방법은 폐기했습니다.
- 결국 책에 나온 답을 참고하여 풀이를 수정했습니다.
$O(N)$
- 구현 문제는 기능 별로 함수를 나누어야겠습니다.
- 문제를 푸는 아이디어가 부족합니다. 더 다양한 문제를 접하며 감을 늘려야겠습니다.
> ch_05-007. 방문 길이

- src/youngrongoh/ch_06/solution_009.py
10분
스택
- 스택
- 10진수의 몫이 1이 될 때까지 나누었을 때 이전에 나온 모든 나머지를 역순으로 나열하기 위해 사용했습니다.
- 처음에는 스택의 요소를 하나씩 `pop()`하면서 문자열에 붙이는 방식으로 구현했습니다. 하지만 이러한 방법이 시간 복잡도를 높인다는 것을 책에서 보고 `reverse()` 후에 `join()` 하는 방식으로 바꾸었습니다.
$O((\log_{}N)^2)$ -> $O(\log_{}N)$
- 로그에 대한 수학 개념을 다 잊어버려서 직접 계산은 못하고 책에 있는대로 기입했습니다. 로그 개념을 학습해야겠습니다.
없습니다.
> ch_06-009. 10진수를 2진수로 변환하기

- src/youngrongoh/ch_06/solution_012.py
30분
스택
책의 답안을 참고해 한 번 더 풀어보았습니다.
시간 복잡도가 $O(N)$이 되려면 항상 반복문을 중첩시키지 않아야 하는 줄 알았습니다. 하지만 for, while문이 중첩되어 있음에도 $O(N)$ 복자도가 나온다는 것이 잘 이해되지 않으면서도 신기했습니다.
$O(N)$
"어떻게 하면 불필요한 연산을 줄일까"를 고민해야겠습니다.
> ch_06-012. 주식가격 - 답안 참고

- src/youngrongoh/ch_06/solution_013.py
20분
스택
- 스택
- 마지막에 들어간 인형과 새로 들어가는 인형이 같은지 비교해야하기 때문에 스택을 사용
인형뽑기가 열 방향으로 움직이기 때문에 열 루프 안에 행 루프가 들어오는 형태로 구현해야 했다.
$O(N^2)$
- 2차원 배열에 대해 중첩 루프로 조회
.
> ch_06-013. 크레인 인형 뽑기 게임

- src/Messe7654/ch_05/solution_001.py
Solution for Problem 001.
약간의 시간
sorted 함수
python에서 기본적으로 제공 되는 list like sorting 함수
.
O(N log N) 으로 추정
.
arr.sort()와 시간 비교 필요
> Messe7654 Solve The Problem 001

- src/Messe7654/ch_05/solution_002.py
3분
set, list
중복값을 제거하는 과정에서 set을 사용해야겠다라고 생각
매력적인 python의 기능 중 하나인 list comprehension을 사용하는 것이 조금 어려웠음
O(N log N)
.
.
> Messe7654 Solve The Problem 002

- src/youngrongoh/ch_06/solution_014.py
1시간
리스트, 스택
- 리스트
- 데이터를 조회, 삭제, 복구할 테이블을 리스트로 사용했습니다.
- 스택
- 삭제된 데이터를 복구할 때 마지막에 실행한 것부터 복구해야 해서 스택을 사용했습니다.
- 리스트를 통해 데이터를 관리하니 중간에 있는 데이터를 삭제, 복구(삽입)할 때 `insert()`, `pop()` 연산에 시간이 많이 소요되었습니다. 이로 인해 효율성 테스트를 실패했습니다.
$O(N(M+1))$
- M개의 커맨드를 순회하는데 $O(M)$, 최악의 경우 테이블 맨 앞에 복구(삽입), 삭제할 때 N개의 데이터를 순회하는데 $O(N)$, N개의 데이터를 `join()`을 사용해 문자열로 변환하는데 $O(N)$
.
- 복구, 삭제 연산에 드는 연산을 줄여야 합니다.
> ch_06-014. 표 편집

- src/Messe7654/ch_05/solution_003.py
2분 (이전 코드 재활용)
set, list, 내장 함수 sorted
Problem 002번와 서로 다른 index를 가지는 두 수의 합으로 구성되는 이라는 조건만이 다름.
서로 다른 두 index는 2중 for문을 통해서 구현 할 수 있기 때문에 해당 내용만 추가하면 된다고 생각.
.
O(N^2 log N)
.
> Messe7654 Solve The Problem 003

- src/youngrongoh/ch_07/solution_016.py
40분
큐
- 큐
- 먼저 완료된 작업부터 순차적으로 목록에서 제거하기 위해 사용했습니다.
- 처음에는 진행율만 큐로 관리하고, 진행 속도를 리스트로 관리했는데 이렇게 되니 큐에서 데이터가 하나 나가는 순간부터 진행 속도 매칭이 틀어지는 문제가 생겼습니다. 그래서 두 가지 데이터를 함께 큐에 넣어서 관리하도록 변경했습니다. 이 문제를 찾는데 시간이 많이 소요되었습니다.
$O(N)$
- 큐 전체를 while문으로 순회하지만 최악의 경우는 첫번째 진행율이 0부터 1의 속도로 오르는 경우이므로 $O(100)$, while문 내에서 큐의 모든 요소의 진행율을 업데이트는데 $O(N)$$
$$O(100) * O(N) = O(100N) = O(N)$$
.
.
> ch_07-016. 기능 개발

- src/youngrongoh/ch_07/solution_017.py
5분
큐
- 큐
-  카드를 순서대로 사용해야하고, 앞에 카드를 사용하지 않고서 뒤에 카드를 사용할 수 없다는 조건을 보고 큐를 사용했습니다.
$O(N)$
> ch_07-017. 카드 뭉치

- src/youngrongoh/ch_08/solution_018.py
30분
- 해시테이블
- 해시 테이블
- 목표값에서 배열의 요소를 뺀 값을 O(1)의 복잡도로 탐색하기 위해 사용했습니다.
$O(N)$
> ch_08-018. 두 개의 수로 특정값 만들기

- src/youngrongoh/ch_08/solution_019.py
10분
- 해시 함수 및 해시 테이블
- 딕셔너리
- 해시 함수 및 해시 테이블
- 문제에 해시 함수를 만들어 사용하라는 조건이 있습니다.
- 딕셔너리
- $O(1)$의 복잡도로 해시 키를 조회하기 위해 해시 테이블을 딕셔너리로 사용했습니다.
해시함수 구현 방법이 수식으로 주어져서 당황했지만, 상수와 변수를 대입해서 코드로 옮기니 문제없이 실행 되었습니다.
$O(N + M)$
- 해시 함수에 입력으로 주어질 수 있는 최대 문자열 길이는 $O(10^6)$, 해시 테이블을 만들 때 `string_list` 전체를 순회하므로 $O(N)$, `query_list` 전체를 순회( $O(M)$ )하며 매번 해시 테이블에 동일한 문자가 있는지 체크( $O(1)$ )하며 탐색하는데 $O(M) \times O(1)$
$$O(N) \times O(10^6) + O(M) \times O(10^6) \times O(1) = O(N) + O(M) = O(N + M)$$
> ch_08-019. 문자열 해싱을 이용한 검색 함수 만들기

- src/youngrongoh/ch_08/solution_020.py
10분
- 해시 테이블(딕셔너리)
완주자 명단에 포함되지 않은 참가자 이름이 있는지 빠르게 탐색하기 위해 완주자 명단을 해시 테이블로 만들어 사용했습니다.
동명이인 처리
- 해시 테이블에서는 키가 같으면 같은 위치에 저장되기 때문에 동명이인을 체크하기 위해 그 수를 해시 키에 대응되는 값으로 저장하였습니다.
$O(N)$
- 완주자 명단으로 해시 테이블을 만드는데 $O(N-1)$, 참가자 명단을 순회하며 해시 테이블을 탐색하는데 $O(N) * O(1)$
$$O(N - 1) + O(N) * O(1) = O(2N) = O(N)$$
> ch_08-020. 완주하지 못한 선수

- src/dayaelee/ch_06/solution_009.py
15분
스택
대상의 몫과 나머지를 스택을 통해 넣어주고 출력을 위해 str을 만들 때도 스택의 꺼내기를 이용함
없음
O(N)
없음
없음
> 문제 009 : 10진수를 2진수로 변환하기

- src/youngrongoh/ch_08/solution_021.py
50분
- 해시 테이블(딕셔너리)
상품 이름과 개수를 매핑하기 위해 상품 이름을 키, 개수를 값으로 하는 해시테이블을 사용했습니다.
- 파이썬에서 두 딕셔너리가 같은 키와 값 쌍으로 구성되었는지 간단히 비교할 수 있다는 것을 몰랐습니다.
- 시간 복잡도를 $O(N)$으로 맞추기 위해 중첩 반복문을 사용하지 않으려 했는데 $O(N) \times O(10)$ 연산을 사용할 수 밖에 없었습니다. 복잡도를 잘 계산해서 상수 횟수의 중첩 순회와 같이 시간 복잡도에 큰 영향을 주지 않는 연산은 걱정하지 않고 사용할 수 있도록 해야겠습니다.
- 구매할 상품 목록으로 딕셔너리 만들 때 $O(10)$, 일별 할인 상품 리스트를 순회할 때 $O(N - 9)$, 10일 동안 살 수 있는 할인 상품을 딕셔너리로 만들 때 $O(10)$
$$O(10) + O(N - 9) \times O(10) = O(10N) - O(80)  = O(N)$$
> ch_08-021. 할인 행사

- src/youngrongoh/ch_08/solution_022.py
- 5분
- 딕셔너리
- 마지막으로 변경한 닉네임만 결과에 반영되기 때문에 아이디에 대응하는 닉네임을 저장해서 결과 출력 전에 넣어주었습니다.
$O(N)$
- 로그를 순회하며 아이디에 대응하는 닉네임을 딕셔너리에 저장하는데 $O(N)$, 로그를 순회하며 결과 문자열을 조립하는데 $O(N)$
$$O(N) + O(N) = O(2N) = O(N)$$
> ch_08-022. 오픈채팅방

- src/youngrongoh/ch_08/solution_023.py
55분
딕셔너리
- 딕셔너리
-  노래 고유번호, 장르, 재생횟수 같은 노래 정보를 저장하기 위해 사용했습니다.
- 장르에 속한 모든 곡의 재생 횟수의 총합을 각 장르별로 매핑하기 위해 사용했습니다.
- 장르 정렬, 노래 정렬을 순회가 중첩되지 않도록 구현하는 것이 어려웠습니다.
$O(N \log_{}N)$
- 노래 정보 목록 생성하는데 $O(N)$
- 생성한 목록을 재생횟수 높은 순으로 정렬하는데 $O(N \log_{}N)$
- 장르별 전체 재생횟수 매핑하는데 최대 $O(N)$
- 전체 재생횟수 높은 순으로 장르 정렬하는데 최대 $O(100 \log_{}100)$
- 정렬한 장르 리스트 순회(최대 $O(100)$ )하면서 장르에 속한 노래 필터링( $O(N)$ )하는데 $O(100) \times O(N)$
$$
\begin{split}
& O(N) + O(N \log_{}N) + O(N) + O(100 \log_{}100) + O(100) \times O(N) \\
& = O(N \log_{}N) + O(102N) + O(100 \times 2) \\
& = O(N \log_{}N) + O(N) \\
& = O(N \log_{}N)
\end{split}
$$
> ch_08-023. 베스트 앨범

- src/BGM-109/ch_05/solution_004.py
- tests/.env
5분
완전 탐색 
모든 가능한 정답 리스트를 탐색해야 했기 때문입니다.
어려운 부분은 없었습니다.
O(N)
테스트 케이스는 추가하지 않았습니다.
현재로서는 개선이 필요한 부분이 명시되어 있지 않습니다.
> ch_05:004 모의고사

- src/BGM-109/ch_05/solution_006.py
- src/BGM-109/ch_05/solution_007.py
25분
리스트
반복문
정렬
주어진 문제를 해결하기 위해 리스트를 사용하여 각 스테이지에 도달한 플레이어 수와 클리어하지 못한 플레이어 수를 추적하고, 정렬을 통해 실패율을 구함.
for 문을 두번 사용하는것을 개선하고 싶었으나 방법을 아직 찾지 못함..
O(N^2) 여기서 N은 스테이지의 개수입니다.
제공된 테스트 케이스 외에 추가한 테스트 케이스는 없습니다.
주어진 문제를 해결하는 데는 큰 문제가 없습니다. 다만, 예외 처리를 피하고 인덱스를 직접 체크하여 코드를 더 깔끔하게 만들었습니다. 코드의 가독성과 유지보수성을 강화하기 위해 주석을 추가하고 변수명을 명확하게 지정하는 것이 좋습니다. 또한, 코드 내에서 예외 처리를 사용하는 것보다 조건문을 통한 범위 체크를 선호하는 것이 좋습니다.
> Bgm 109/006

- src/BGM-109/ch_05/solution_007.py
20분
없음
없음
범위가 벗어난 경우를 나중에 추가했다. 문제를 잘 읽어야 될것 같다.
튜플을 활용했는데 매우 직관적인것같다. 
O(N) (dir의길이)
없습니다
1. trace 리스트를 처음 부터 set으로 선언해도될것같다.
> 5장 배열 : 방문 길이

- src/BGM-109/ch_06/solution_012.py
30분
스택
주어진 문제를 해결하기 위해 스택을 활용하여 중복 계산을 피하고, 시간 복잡도를 O(N)으로 최적화함.
스택의 개념 및 활용 방법에 대한 이해가 필요했던 부분
O(N)
제공된 테스트 케이스 외에 추가한 테스트 케이스는 없습니다.
주어진 문제를 해결하는 데 큰 문제가 없습니다. 다만, 스택의 개념과 활용에 조금 더 익숙해지면 더욱 효과적인 코드를 작성할 수 있을 것입니다. 이를 위해 스택에 관한 추가적인 학습이 도움이 될 수 있습니다.
> ch_06 스택 : 주식가격

- src/youngrongoh/ch_08/solution_024.py
60분
딕셔너리, 셋
- 딕셔너리
- 사용자 마다 어떤 사용자를 신고했는지 저장하기 위해 사용했습니다.
- 셋
- 같은 사용자가 동일한 사용자를 여러 번 신고한 경우, 중복을 제거하기 위해 사용했습니다.
$O(N + M)$
- 신고 기록을 순회하며 사용자별 신고 대상을 추출한 딕셔너리를 만드는데 $O(M)$
- 사용자별 신고 대상 딕셔너리를 순회하며 사용자별 신고당한 횟수 딕셔너리를 만드는데 최악의 경우는 동일한 사용자에 대한 신고가 없는 경우이므로 $O(200,000)$
- 사용자마다 받는 이메일 갯수를 계산하는데, 신고 기록은 최대 200,000번으로 제한 됨. 따라서, 한 사람당 신고할 수 있는 횟수는 최악의 경우, 즉 중복 신고가 없는 경우라고 해도 상수 횟수로 한정되기 때문에 $O(N \times C) = O(N)$ ($C \leq M/N$, $M \leq 200000$)
$$ O(M) + O(200000) + O(N) = O(N + M) $$
> ch_08-024. 신고 결과 받기

- src/youngrongoh/ch_08/solution_025.py
- 3시간
- 딕셔너리
- 딕셔너리
- 음식 조합의 주문 횟수를 저장하기 위해 사용했습니다.
- 가능한 조합을 모두 찾으면서 주문 횟수를 만드는 로직이 어려웠습니다. 반복문 중첩이 많아질수록 시간복잡도에 문제가 없을지, 이렇게 푸는게 맞는 것인지 걱정되어서 집중이 잘 되지 않았습니다.
- 코스 요리로 구성하고 싶은 최대 음식 개수와 손님들이 주문한 최대 음식 개수가 달라서 한 쪽의 최대값을 참조하니 인덱스 에러가 발생하는 케이스가 있었습니다. 처음에는 이 문제를 인지하지 못했습니다.
잘 모르겠습니다.
$O()$
- ~주문 목록을 순회하는데 $O(N)$~
- ~가능한 코스 요리 개수를 순회하는데 $O(N-1)$~
- ~ 모든 경우의 수를 찾는데 $O(N!/R! \times (N - R)!)$ ($2 \leq R \leq 10$)~
- ~코스 요리 개수 목록을 순회하는데 최악의 경우 $O(10)$~
- ~각각의 요리 개수에 따라 모든 경우의 수를 순회하는데 $O(N!/R! \times (N - R)!)$ ($2 \leq R \leq 10$)~
- ["XYZ", "XYZ"], [3]
- 처음에 course에 포함된 케이스만 추출했는데 로직을 이전 조합을 기반으로 구하도록 구현해서 course 배열에 2부터 시작되는 연속된 정수가 아니면 결과가 잘못 나오는 경우가 있었습니다. 이를 체크하기 위해 추가하였습니다.
- 반복문의 반복 조건이 복잡해지면 시간 복잡도 게산을 어떻게 해야할지 모르겠습니다.
- 문제를 푸는데 너무 오래 걸렸습니다.
> ch_08-025. 메뉴 리뉴얼

- src/BGM-109/ch_05/solution_006.py
- src/BGM-109/ch_06/solution_013.py
30분
스택 
인형을 떠트리는 부분을 스택을 사용하여 짝을 맞춤 
스택을 사용한다는 점을 알고 접근해 비교적 쉽게 해결했습니다. 짝을 맞춘다는 포인트에서 스택에 대한 힌트를 쉽게 얻을 수 있을 것같습니다.
O(m x n ^ 2)
m = moves 
n = board 의 크기 
테스트를 추가하진않았지만, moves 의 길이나, moves 요소의 범위 행렬의 크기에 대해서 고려해 볼수있습니다.
`rotate_matrix` 함수에서 새로운 행렬을 생성하고 값을 복사하는 방식으로 회전을 구현하고 있습니다. 이 부분을 개선하여 원본 행렬을 직접 회전시키는 방법을 고려할 수 있습니다.
> ch_06: 크레인인형뽑기

- src/youngrongoh/ch_09/solution_027.py
50분
이진 탐색 트리(리스트)
- 이진 탐색 트리(리스트)
- 이진 탐색 트리를 구현 하라는 문제이기 때문에 사용했습니다.
- 상대적으로 구현 난이도가 쉬운 리스트로 구현했습니다.
리스트 범위를 벗어나는 인덱스에 값을 삽입하려고 하면 에러가 발생했습니다. 이를 해결하기 위해 삽입할 인덱스 위치까지 먼저 빈 값을 삽입하도록 했습니다. 이렇게 이진 탐색 트리를 리스트로 구현해보니 빈 값이 차지하는 공간이 상당히 많다는 것을 체감했습니다.
$O(N \times log_{}N)$
- $N$개의 값으로 이진 탐색 트리를 만드는데 $O(N \times log_{}N)$
- 최대 10개의 값이 이진 탐색 트리에 존재하는지 탐색 하는데 $O(10 \times log_{}N)$
$$ O(N \times log_{}N) + O(10 \times log_{}N) \approx O(N \times log_{}N)$$
> ch_08-027. 이진 탐색 트리 구현

- src/youngrongoh/ch_09/solution_028.py
50분
완전 이진 트리
- 완전 이진 트리
- 부전승이 없는 대진표 형태이므로 완전 이진 트리의 특성을 이용하였습니다.
- 공비수열의 합을 구하는 방법을 잊어버려서 문제를 풀던 중간에 다시 학습하고 문제를 풀었습니다.
- 입력으로 주어진 N을 바로 공비수열의 합공식에 대입하여 사용하는 것이 아니라, 로그를 취해서 사용해야 한다는 것을 놓쳐서 시간을 많이 보냈습니다.
$O(\log_{2}N)$
- 최악의 경우 루트 레벨까지 올라가야 하므로 반복횟수는 최대 $\log_{2}N$번
> ch_09-028. 예상 대진표

- src/youngrongoh/ch_10/solution_034.py
5분
집합
중복제거를 위해 사용했습니다.
$O(N)$
- nums 리스트를 집합으로 변환할 때 $O(N)$
> ch_09-034. 폰켓몬

- src/youngrongoh/ch_10/solution_035.py
10분
집합
이미 말한 단어에 포함되는지 $O(1)$의 복잡도로 체크하기 위해 사용했습니다.
$O(N)$
- words를 한 번 순회하는데 $O(N)$
> ch_10-035. 영어 끝말잇기

- src/youngrongoh/ch_10/solution_036.py
50분
사전식 정렬
사전식 정렬을 하면 phone_book에 담긴 모든 번호를 체크할 필요가 없기 때문에 사용했습니다.
사전식 정렬을 사용했지만, 바로 뒤에 문자만 체크하면 된다는 것을 생각하지 못했습니다.
$O(Nlog_{}N)$
- phone_book을 정렬하는데 $O(Nlog_{}N)$
- 정렬한 phone_book을 순회하는데 $O(N-1)$
> ch_10-036. 전화번호 목록

- src/youngrongoh/ch_10/solution_033.py
30분
집합
집합과 그 메서드(`union`, `find`) 구현 문제이기 때문에 사용했습니다.
경로 압축, 랭크를 적용해 연산을 최적화하는 것
- find: $O(N)$, 경로압축 적용 시 $O(\alpha(N)) \approx O(1) \text{(} \alpha \text{는 역 아커만 함수 )}$
- union: $O(N)$, 경로압축 적용 시 $O(\alpha(N)) \approx O(1)  \text{(} \alpha \text{는 역 아커만 함수 )}$
> ch_10-033. 간단한 유니온-파인드 알고리즘 구현하기

- src/Messe7654/ch_05/solution_005.py
- src/Messe7654/ch_05/solution_006.py
약 8분
List
prefix sum
실패율의 계산에 누적 도달한 사람의 수가 필요했기에 prefix sum technique을 사용
실질적으로 시간 복잡도 상의 이득을 취하지는 않음
prefix sum을 우측에서부터 하는 것이 익숙하지 않다보니 Table을 1 더 크게 하는 것을 생략하여 오류가 발생함
O(N log N + len(stages))
> Messe7654 Solve The Problem 006

- src/Messe7654/ch_06/solution_010.py
15분
Stack
008번과 같은 이유로 Stack 자료구조를 사용함.
달라진 점은 문자열을 left_rotate하는 것에 대한 개념이 필요하였음
.
O(N^2)
.
.
> Messe7654 Solve The Problem 010
